clc;
clearvars;
My_fis=mamfis('Name',"Fuzzy_Controller","AndMethod","prod","DefuzzificationMethod","centroid");
num_inputs=2;
My_fis=addInput(My_fis,[-1 1],'Name',"Error");
My_fis=addInput(My_fis,[-1 1],'Name',"Rate_of_error");
My_fis=addOutput(My_fis,[-1 1],'Name',"OP");
num_input_MFs=7;
input_mf_names=["NB";"NM";"NS";"ZE";"PS";"PM";"PB"];
params_input_MF(:,:,1)=[-1000 -1 -0.7;-1 -0.7 -0.35;-0.7 -0.35 0;-0.35 0 0.35;0 0.35 0.7;0.35 0.7 1;0.7 1 1000];
params_input_MF(:,:,2)=[-1000 -1 -0.7;-1 -0.7 -0.35;-0.7 -0.35 0;-0.35 0 0.35;0 0.35 0.7;0.35 0.7 1;0.7 1 1000];
for i=1:num_inputs
    for j=1:num_input_MFs
        My_fis=addMF(My_fis,My_fis.Inputs(i).name,"trimf",params_input_MF(j,:,i),'Name',input_mf_names(j));
    end
end
op_mf1=fismf("zmf",[-0.9 -0.6],'Name',"NB");
op_mf2=fismf("gaussmf",[0.2 -0.65],'Name',"NM");
op_mf3=fismf("gaussmf",[0.2 -0.35],'Name',"NS");
op_mf4=fismf("gaussmf",[0.2 0],'Name',"ZE");
op_mf5=fismf("gaussmf",[0.2 0.35],'Name',"PS");
op_mf6=fismf("gaussmf",[0.2 0.65],'Name',"PM");
op_mf7=fismf("smf",[0.5 0.9],'Name',"PB");
My_fis.Outputs(1).MembershipFunctions=[op_mf1 op_mf2 op_mf3 op_mf4 op_mf5 op_mf6 op_mf7];
My_fis=addRule(My_fis,["Error==NB & Rate_of_error==NB=>OP=NB"...
    "Error==NB & Rate_of_error==NM=>OP=NB"...
    "Error==NB & Rate_of_error==NS=>OP=NB"...
    "Error==NB & Rate_of_error==ZE=>OP=NB"...
    "Error==NB & Rate_of_error==PS=>OP=NM"...
    "Error==NB & Rate_of_error==PM=>OP=NS"...
    "Error==NB & Rate_of_error==PB=>OP=ZE"...
    "Error==NM & Rate_of_error==NB=>OP=NB"...
    "Error==NM & Rate_of_error==NM=>OP=NB"...
    "Error==NM & Rate_of_error==NS=>OP=NB"...
    "Error==NM & Rate_of_error==ZE=>OP=NM"...
    "Error==NM & Rate_of_error==PS=>OP=NS"...
    "Error==NM & Rate_of_error==PM=>OP=ZE"...
    "Error==NM & Rate_of_error==PB=>OP=PS"...
    "Error==NS & Rate_of_error==NB=>OP=NB"...
    "Error==NS & Rate_of_error==NM=>OP=NB"...
    "Error==NS & Rate_of_error==NS=>OP=NM"...
    "Error==NS & Rate_of_error==ZE=>OP=NS"...
    "Error==NS & Rate_of_error==PS=>OP=ZE"...
    "Error==NS & Rate_of_error==PM=>OP=PS"...
    "Error==NS & Rate_of_error=PM=>OP=PM"...
    "Error==ZE & Rate_of_error==NB=>OP=NB"...
    "Error==ZE & Rate_of_error==NM=>OP=NM"...
    "Error==ZE & Rate_of_error==NS=>OP=NS"...
    "Error==ZE & Rate_of_error==ZE=>OP=ZE"...
    "Error==ZE & Rate_of_error==PS=>OP=PS"...
    "Error==ZE & Rate_of_error==PM=>OP=PM"...
    "Error==ZE & Rate_of_error==PB=>OP=PB"...
    "Error==PS & Rate_of_error==NB=>OP=NM"...
    "Error==PS & Rate_of_error==NM=>OP=NS"...
    "Error==PS & Rate_of_error==NS=>OP=ZE"...
    "Error==PS & Rate_of_error==ZE=>OP=PS"...
    "Error==PS & Rate_of_error==PS=>OP=PM"...
    "Error==PS & Rate_of_error==PM=>OP=PB"...
    "Error==PS & Rate_of_error==PB=>OP=PB"...
    "Error==PM & Rate_of_error==NB=>OP=NS"...
    "Error==PM & Rate_of_error==NM=>OP=ZE"...
    "Error==PM & Rate_of_error==NS=>OP=PS"...
    "Error==PM & Rate_of_error==ZE=>OP=PM"...
    "Error==PM & Rate_of_error==PS=>OP=PB"...
    "Error==PM & Rate_of_error==PM=>OP=PB"...
    "Error==PM & Rate_of_error==PB=>OP=PB"...
    "Error==PB & Rate_of_error==NB=>OP=ZE"...
    "Error==PB & Rate_of_error==NM=>OP=PS"...
    "Error==PB & Rate_of_error==NS=>OP=PM"...
    "Error==PB & Rate_of_error==ZE=>OP=PB"...
    "Error==PB & Rate_of_error==PS=>OP=PB"...
    "Error==PB & Rate_of_error==PM=>OP=PB"...
    "Error==PB & Rate_of_error==PB=>OP=PB"...
    ]);
%figure(1)
%plotmf(My_fis,'input',1);
%figure(2)
%plotmf(My_fis,'output',1);
%gensurf(My_fis);
%evalfis(My_fis,[0.5 -0.3])
writeFIS(My_fis,'Fuzzy_PD');